Timur iskahov motivation spectrum
tlbootcamp/tlroadmap pull request #330
Opened 2020-08-09 13:46 UTC by TimurIskahov

Модель спектр мотивации

2020-09-10 06:31 UTC, DevAlloy commented on tlroadmap/roles/people-manager/people-management/motivation/ru.md
> +
Слишком много пустых строк

2020-09-10 09:28 UTC, etolstoy requested changes

2020-09-10 09:28 UTC, etolstoy commented on tlroadmap/roles/people-manager/people-management/motivation/ru.md
> +#### Модель спектр мотивации
Кавычки, наверное

2020-09-10 09:28 UTC, etolstoy commented on tlroadmap/roles/people-manager/people-management/motivation/ru.md
> +Состояния в модели спектр мотивации разделены на неоптимальные и оптимальные. Три из них маркированы как неоптимальные: автоматический, внешний и навязанный. Их можно сравнить с некачественной пищей.
И тут кавычки тоже

2020-09-16 19:01 UTC, etolstoy approved these changes

2020-09-17 05:57 UTC, TimurIskahov commented
Похоже раньше времени закрыл

2020-10-18 12:14 UTC, TimurIskahov commented
@DevAlloy доброго вечера. 
Я ведь правильно помнимаю, что сейчас для мержа нужен твой approve?

2020-10-18 12:21 UTC, DevAlloy approved these changes

2020-10-18 12:21 UTC, merged