Test design
tlbootcamp/tlroadmap pull request #376
Opened 2022-01-05 15:28 UTC by redfoks

2022-01-09 12:23 UTC, DevAlloy approved these changes

2022-01-13 13:47 UTC, etolstoy requested changes

2022-01-13 13:47 UTC, etolstoy commented on tlroadmap/roles/technical-lead/product-quality/testing/test-design/ru.md
> +Для разработчика
Потеряно двоеточие

2022-01-13 13:47 UTC, etolstoy commented on tlroadmap/roles/technical-lead/product-quality/testing/test-design/ru.md
> +- с помощью тест-дизайн проще покрыть основные риски
тест-дизайнА

2022-01-13 13:47 UTC, etolstoy commented on tlroadmap/roles/technical-lead/product-quality/testing/test-design/ru.md
> +
Лишняя пустая строка

2022-01-13 13:47 UTC, etolstoy commented on tlroadmap/roles/technical-lead/product-quality/testing/test-design/ru.md
> +
Тут и далее тоже лишние пустые строчки

2022-01-13 13:47 UTC, etolstoy commented on tlroadmap/roles/technical-lead/product-quality/testing/test-design/ru.md
> +- Чат, сообщество, люди, к которым можно обратиться.
Тут бы добавить какие-то релевантные QA чаты

2022-01-13 13:47 UTC, etolstoy commented on tlroadmap/roles/technical-lead/product-quality/testing/test-design/ru.md
> +- Lee Copeland. A Practitioner's Guide to Software Test Design
Нужна ссылка

2022-01-14 20:36 UTC, redfoks commented on tlroadmap/roles/technical-lead/product-quality/testing/test-design/ru.md
> +- Чат, сообщество, люди, к которым можно обратиться.
Добавила

2022-01-17 08:12 UTC, merged

2022-01-17 08:12 UTC, etolstoy commented
Смерджил, спасибо :)